apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: karsajobs
spec:
  ports:
    - port: 27017
  selector:
    tier: data
  # headless service untuk dapat dikoneksi oleh pod lain
  clusterIP: None
