apiVersion: v1
kind: Service
metadata:
  name: frontend-tier
  labels:
    app: karsajobs
spec:
  ports:
    - port: 8000
  selector:
    tier: frontend
  # NodePort untuk mengekpose service ke port tertentu sehingga bisa diakses
  type: NodePort
