apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order
  template:
    metadata:
      labels:
        app: microservices
        name: order
    spec:
      containers:
        - name: order-service
          image: ghcr.io/stevan11leonardy/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: AMQP_URL
              value: amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_SERVICE_HOST):5672
