apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: microservices
spec:
  ports:
    - port: 3000
  selector:
    name: order
  # NodePort untuk mengekpose service ke port tertentu sehingga bisa diakses
  type: NodePort
